name: Publish API spec

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install raml2html
        run: |
          sudo rm /etc/apt/sources.list* /etc/apt/sources.list.d/*
          sudo printf "Enabled: yes\nTypes: deb\nURIs: http://azure.archive.ubuntu.com/ubuntu/\nSuites: focal focal-updates focal-backports focal-security\nComponents: main universe multiverse restricted\n" | sudo tee /etc/apt/sources.list.d/system.sources
          sudo apt-get -qq update && sudo apt-get -qq install --assume-yes --no-install-recommends npm
          sudo npm install --global --silent raml2html

      - name: Build webpage from RAML file
        run: |
          mkdir gh-pages
          raml2html scraf.raml --output gh-pages/index.html

      - name: Publish page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          cname: api.scraf.pwrau.ml
