name: Publish API spec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install raml2html
        run: |
          sudo apt-get -qq update && sudo apt-get -qq install --assume-yes --no-install-recommends npm
          sudo npm install --global raml2html
      
      - name: Build webpage from RAML file
        run: |
          mkdir gh-pages
          raml2html scraf.raml --output gh-pages/index.html
      
      - name: Publish page
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          cname: api.scraf.pwrau.ml
